server:
  port: 8185
spring:
  redis:
    ###################以下为redis单机模式配置###########################
    host: 117.50.175.161    # Redis服务器地址
    port: 6379         # Redis服务器连接端口
    database: 0        # Redis数据库索引（默认为0）
    password: fk6258077   # Redis服务器连接密码（默认为空）
    timeout: 3000      # 连接超时时间（毫秒）
    ###################以下为redis哨兵增加的配置###########################
    ##哨兵里连接节点的ip,虽然在内网但也要写真实ip,不然永远跳转到127
    #password: 807766   # Redis服务器连接密码（默认为空）
    #sentinel:
      #nodes: 159.138.46.191:26379,159.138.46.191:26380,159.138.46.191:26381 # 集群哨兵节点配置，多个节点之间用英文逗号分割
      #master: mymaster # Redis主节点名称，哨兵配置文件中的名称
    lettuce: # Redis的Java驱动包,使用lettuce连接池
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10    # 连接池中的最大空闲连接 (默认为8)
        min-idle: 0     # 连接池中的最小空闲连接
  jersey:
    application-path: zj
mybatis:
  # 指定 WeChatMediaInfoDao.xml 的位置
  mapper-locations: classpath:mapper/*.xml
  #扫描实体类的位置,在此处指明扫描实体类的包，在 WeChatMediaInfoDao.xml 中就可以不写实体类的全路径名
  type-aliases-package: com.zj.wechat.entity
  configuration:
    #默认开启驼峰命名法，可以不用设置该属性
    map-underscore-to-camel-case: true
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
seata:
  enabled: true
  application-id: ${spring.application.name} #项目名称,默认spring.application.name
  tx-service-group: default_tx_group
  enable-auto-data-source-proxy: true #可以不写,默认开启自动代理
  data-source-proxy-mode: AT #默认的就是AT
  config:
    type: nacos
    nacos:
      namespace: 38dad4f3-1581-41a2-85ae-745d6734dc21
      serverAddr: 117.50.175.161:8848
      group: zjdev
      userName: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 117.50.175.161:8848
      namespace: 38dad4f3-1581-41a2-85ae-745d6734dc21
      group: zjdev
      userName: "nacos"
      password: "nacos"
      cluster: default
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist: #集群名称-seata地址
      default: 117.50.175.161:8091
