server:
  port: 8185
spring:
  jersey:
    application-path: zj
  datasource:
    url: jdbc:mysql://159.138.46.191:3306/wechat?useSSL=false&serverTimezone=UTC
    username: wechat
    password: fk6258077
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    username: 279976891@qq.com
    password: zcmojevyvijxcbcg
    host: smtp.qq.com
mybatis:
  # 指定 WeChatMediaInfoDao.xml 的位置
  mapper-locations: classpath:mapper/*.xml
  #扫描实体类的位置,在此处指明扫描实体类的包，在 WeChatMediaInfoDao.xml 中就可以不写实体类的全路径名
  type-aliases-package: com.zj.wechat.entity
  configuration:
    #默认开启驼峰命名法，可以不用设置该属性
    map-underscore-to-camel-case: true
cfg:
  token: fk6258077zj
  appId: wx0634de833b901930
  appSecret: 2fbc2b70491fc6dec2144bd85aa97bbb
  gprToken: Bearer eyJraWQiOiJOREpXM05UTkI2MWlTQSs0SE41RW54Wk93WWtuYmpFRGVpQStxU01WSHN3PSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI2YmFkZTdjMy0xZTNiLTRlODEtYmZhMS00YWY1NDk4ZmZjYWIiLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuYXAtbm9ydGhlYXN0LTEuYW1hem9uYXdzLmNvbVwvYXAtbm9ydGhlYXN0LTFfMXFwaXA2cnV2IiwiY29nbml0bzp1c2VybmFtZSI6InRtcng1d3llbW5kNmxqNjRnMXRydmQiLCJvcmlnaW5fanRpIjoiYjg3MmQ0NDQtM2NhOS00NWRlLTliNzItNzhkODgzMDdhYmE4IiwiYXVkIjoiMjAxcXBlZW11djdlMWhic3BhcDBwMmRjcTAiLCJldmVudF9pZCI6ImE0OWVhZDQwLWNlODEtNGQ5OC1hOGVjLTQxOTExNDVkMmU4OSIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNjc5NjcyMDY1LCJwaG9uZV9udW1iZXIiOiIrODYxNzc4MzExNDM0OCIsImV4cCI6MTY3OTY3OTg2OSwiaWF0IjoxNjc5Njc2MjY5LCJqdGkiOiJmMzRhYzUwYi0yYmI2LTQ2NmMtOTM1OC1iMGIyMDlmODFjOTkifQ.YSlidh4nLJDwYwp2QCYmPsER5wFfOHABycVIC5L6aC4rxMOyOEXl4PvWNlI9FHUQmv9owmgiqIME-GClJZ7dMLa8GCf1T5Imh2uNmSL2nYBdHMJvcfP_uj6wmZVGLXbpcCanUcMYSGok4KKzLbkoySsgGbLfjOgmSsY_hhtUR-VCD2AfMvF92vMIp7wB41mXjBzwjhGj9f0cGxpTxEya1m4OMLHDYozoknOAv0sqbzlygNEgm3_w9WguRV7_cWCy5gAIPFYt4FODU2GKzJNJ2AotIYKgKG2TpRVEGbljvh9hkJpbGRCeSGJwfzN7s9dQEqoluoypAOTeKU0HSBeGUA
