server:
    port: 8080
logging:
    config: classpath:logback-cicd.xml
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.cbiot.entity
    configuration:
        map-underscore-to-camel-case: true
