server:
  port: 8080
logging:
  config: classpath:logback-cicd.xml
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cbiot.entity
  configuration:
    map-underscore-to-camel-case: true
feign:
  circuitbreaker:
    enabled: true
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
          loggerLevel: FULL
spring:
  redis:
    ###################以下为redis单机模式配置###########################
    host: 10.12.6.230    # Redis服务器地址
    port: 6379         # Redis服务器连接端口
    database: 0        # Redis数据库索引（默认为0）
    password: Osms@123   # Redis服务器连接密码（默认为空）
    timeout: 3000      # 连接超时时间（毫秒）
      ###################以下为redis哨兵增加的配置###########################
      ##哨兵里连接节点的ip,虽然在内网但也要写真实ip,不然永远跳转到127
      #password: 807766   # Redis服务器连接密码（默认为空）
      #sentinel:
      #nodes: 159.138.46.191:26379,159.138.46.191:26380,159.138.46.191:26381 # 集群哨兵节点配置，多个节点之间用英文逗号分割
    #master: mymaster # Redis主节点名称，哨兵配置文件中的名称
    lettuce: # Redis的Java驱动包,使用lettuce连接池
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10    # 连接池中的最大空闲连接 (默认为8)
        min-idle: 0     # 连接池中的最小空闲连接