server:
  port: 8185
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: wechat
    password: fk6258077
    url: jdbc:mysql://1.95.44.208:3306/wechat?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&allowMultiQueries=true
    dynamic:
      druid:
        initial-size: 5
        min-idle: 1
        max-active: 10
        max-wait: 6000
        filters: stat,slf4j
  jersey:
    application-path: zj
  mail:
    host: smtp.example.com
    port: 587
    username: 279976891@qq.com
    password: password
mybatis:
  # 指定 WeChatMediaInfoDao.xml 的位置
  mapper-locations: classpath:mapper/*.xml
  #扫描实体类的位置,在此处指明扫描实体类的包，在 WeChatMediaInfoDao.xml 中就可以不写实体类的全路径名
  type-aliases-package: com.zj.wechat.entity
  configuration:
    #默认开启驼峰命名法，可以不用设置该属性
    map-underscore-to-camel-case: true
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
cfg:
  appId: wx0634de833b901930
  appSecret: d48959c66143d3c8ea9c1b20b319f7fe